### ISSUE TITLE
Prompt appears after each call

### ISSUE THREAD

**Issue by mahdifani14** [jorangreef/sudo-prompt#42] opened 2017-02-15 12:20 UTC
Hello,

Scenario: I have several commands to be executed along with my application and they all needs admin privilege.
Problem: I would like to use your module, but whenever I run a command through it, it is asking for the password while I just want to have the prompt once at the beginning.

Do you have any idea?

**Comment by jorangreef** [comment] 2017-02-15 14:41
Thanks, I think this is a duplicate of https://github.com/jorangreef/sudo-prompt/issues/39

Please see the suggestion there.

**Closed by jorangreef** 2017-02-15 14:41 UTC

**Comment by mahdifani14** [comment] 2017-02-15 14:47
@jorangreef Thanks for fast reply, I have seen that issue, but in my case, I have to run the commands in different stages of the application execution, I mean that they are not in a row.

**Comment by jorangreef** [comment] 2017-02-15 15:07
Thanks @mahdifani14, it's not possible. Not because of sudo-prompt, but because sudo itself on Linux and Mac uses TTY tickets. Each time sudo-prompt runs it's essentially running in a new TTY (a new child process), so sudo itself thinks it needs to prompt for a password again. If the user does not have TTY tickets enabled for sudo, then sudo-prompt will only prompt the first time.

**Comment by mahdifani14** [comment] 2017-02-15 15:16
@jorangreef 
I got it.
I'll check other possibilities to overcome this obstacle.
Anyway, thanks again for your support.

**Comment by jorangreef** [comment] 2017-02-16 08:05
It's a pleasure, thanks for checking. You could try using sudo-prompt to launch a long-lived process with root privileges which you could then use to launch your commands as and when needed. If there is another way please let me know.

**Comment by mahdifani14** [comment] 2017-02-17 11:40
@jorangreef Grateful for the hint, I'll try it and inform you about the result or any other solution if I found.

**Comment by mahdifani14** [comment] 2017-02-23 15:13
@jorangreef Eventually after a long ride over this issue, I found a solution and decided to share it with you maybe would be useful. Actually, I tried the idea that you stated but, it didn't work due to the Electron and NodeJs limitations and it's not possible to run the whole app using sudo-prompt.
Therefore, after lots of researches, I divided the story into two scenarios w.r.t the platforms Windows and OSX/Linux.
For the first case, I'm using mt.exe as one of the Windows SDK through which I can force the user to accept the application run as Administrator; for more info, check this link: http://layer0.authentise.com/electron-and-uac-on-windows.html
For latter one, I'm using a mixture of the original sudo and sudo-prompt which is working fine through command line but, the graphical functionality is still under construction and whenever I finalized it, I'll let you know.

**Comment by jorangreef** [comment] 2017-02-23 15:30
Thanks for the link @mahdifani14, that's really helpful.

**Comment by jorangreef** [comment] 2017-02-24 10:19
Have you tested macOS Sierra? There was a change recently so that macOS Sierra has started using TTY tickets. macOS Sierra should require a password for each separate sudo-prompt call.

**Comment by mahdifani14** [comment] 2017-02-24 11:21
@jorangreef Good question, no I didn't. I'll check it and let you know because my application must be cross-platform.
Grateful for the point,

**Comment by Muneefm** [comment] 2018-01-09 18:35
@mahdifani14  @jorangreef  have you found any solution yet?  
am new to this electron.  I needed to open specific .app file from mac application.  so i tried to run  "open  path/to/the/application.app"  it was showing some error.  so i used this library and run the same command now it's working. but the only problem is it's showing the password prompt for every exec.  is there is any way to ask that only one time? Thank you.

**Comment by mahdifani14** [comment] 2018-01-09 22:32
@Muneefm I finally used Cocoasudo, it works fine for all OSX versions, check the link below:
http://www.performantdesign.com/2009/10/26/cocoasudo-a-graphical-cocoa-based-alternative-to-sudo/

**Comment by jorangreef** [comment] 2018-01-10 07:43
@Muneefm TTY tickets are now the default on macOS Sierra onwards.

Each shell session must authenticate as sudo, independently of existing sudo sessions.

You can think of sudo-prompt as launching the equivalent of an authenticated shell session, which is why each session requires a password.

You can either batch up your commands, or disable TTY tickets.

**Comment by NargisTahara** [comment] 2019-03-01 15:39
@Muneefm How did you use cocoasudo with Electron?

**Comment by hb1998** [comment] 2019-10-12 10:57
> @jorangreef You're welcome.
> Mac OSX has been tested by sudo-prompt and worked fine. After running the first command, it keeps the session and uses for the others so, the prompt just appears once.
> However, for Linux case, I have to execute the application by using 'gksudo' in the terminal (Electron runs the application by executing a command in terminal `"start": "gksudo node_modules/.bin/electron ."`) that's why I cannot use sudo-prompt for this matter.

can u explain it in detail for Linux. Thank you.

**Comment by toioski** [comment] 2021-04-27 13:04
Did anyone find a solution to this? It would be really helpful. Personally I am interested on a solution for macOS.
