### ISSUE TITLE
sudo-prompt does not work on electron

### ISSUE THREAD

**Issue by diaxotora** [jorangreef/sudo-prompt#101] opened 2019-06-20 10:44 UTC
Hello Jorangreef,
firstly I just started in nodejs, I have quite low knowledge, by cons I have a pretty good level in javascript and linux, my prombleme is that I want to create an application on electron and I would like to integrate the sudo-prompt module in, so i first tried the example given on the npm site and when i run the application i have a permissions error and the prompt does not appear,
here is the content of my index.js file :
`var sudo = require('sudo-prompt');
var options = {
  name: 'Electron'
};

document.getElementById("submit").addEventListener("click", () => {
	sudo.exec('echo hello', options,
	function(error, stdout, stderr) {
    if (error) throw error;
    console.log('stdout: ' + stdout);
  }
);
});`
and here is the content of my index.html file : 
`<body>
	<br/><br/>
	<input type="submit" id="submit" value="Submit">
	<script src="index.js"></script>
</body>`
and here is the error displayed when I try to launch the application :
`Uncaught Error: User did not grant permission.
    at /home/karim/projets/Test/node_modules/sudo-prompt/index.js:111
    at ChildProcess.exithandler (child_process.js:315)
    at ChildProcess.emit (events.js:194)
    at maybeClose (internal/child_process.js:998)
    at Socket.<anonymous> (internal/child_process.js:403)
    at Socket.emit (events.js:194)
    at Pipe.<anonymous> (net.js:593)`
I hope you can help me because I can not create my application without the integration of this module.

**Comment by jorangreef** [comment] 2019-06-20 16:06
Thanks @diaxotora I am closing this as a duplicate of https://github.com/jorangreef/sudo-prompt/issues/100

The issue is with Electron, using a sandbox to prevent you from escalating.

**Closed by jorangreef** 2019-06-20 16:06 UTC
